import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Alert, ActivityIndicator } from 'react-native';
import Icon from 'react-native-vector-icons/Feather';
import db from '../database/Database'; 

const ALUNOS_CARGA_INICIAL = 
[
  {
    "nome": "José Tiago Toledo da Silva",
    "cpf": "342.544.168-06",
    "data_nasc": "27/02/1987",
    "email": "jtiagotoledo@yahoo.com.br",
    "celular": 5515997010030,
    "logradouro": "Av. das Figueiras",
    "numero": 162,
    "complemento": "Casa 5",
    "bairro": "Vossoroca",
    "cidade": "Votorantim",
    "uf": "SP",
    "cep": "18119-375",
    "lim_aulas": 8
  },
  {
    "nome": "Alessandra A. Alves",
    "cpf": "190.370.748-83",
    "data_nasc": "14/09/1973",
    "email": "",
    "celular": 5515991091322,
    "logradouro": "Rua Tocantins",
    "numero": 213,
    "complemento": "",
    "bairro": "Vila Jardini",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Ana Laura T. Prado",
    "cpf": "138.997.888-94",
    "data_nasc": "31/03/1969",
    "email": "anatezolini@gmail.com.br",
    "celular": 5515988123480,
    "logradouro": "Rua Guarani",
    "numero": 122,
    "complemento": "",
    "bairro": "Vila Jardini",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Anna Carmela Ferro Bordieri Marinheiro",
    "cpf": "306.629.178-20",
    "data_nasc": "06/07/1982",
    "email": "ca.marinheiro@yahoo.com.br",
    "celular": 5515991317469,
    "logradouro": "Rod. Raposo Tavares",
    "numero": "",
    "complemento": "km 108,5",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Ana Lúcia Marques",
    "cpf": "041.892.248-98",
    "data_nasc": "26/07/1961",
    "email": "anamarques2607@gmail.com",
    "celular": 5515992010102,
    "logradouro": "Rua Alemanha",
    "numero": 271,
    "complemento": "",
    "bairro": "Jardim Europa",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Ana Maria Salcedo",
    "cpf": "093.913.038-62",
    "data_nasc": "27/05/1959",
    "email": "ana27salcedo@gmail.com",
    "celular": 5515997257366,
    "logradouro": "Gustavo Teixeira",
    "numero": 148,
    "complemento": "",
    "bairro": "Vila Independência",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Ana Rosa Gomes",
    "cpf": "110.247.648-00",
    "data_nasc": "06/09/1968",
    "email": "ana.malavazai@unidadekumon.com.br",
    "celular": 5515981082948,
    "logradouro": "Luiz Silva Rodrigues",
    "numero": 307,
    "complemento": "",
    "bairro": "Vila Independência",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Antônia Sônia Maldonado",
    "cpf": "069.142.108-02",
    "data_nasc": "25/01/1951",
    "email": "giluanna",
    "celular": 5515981810441,
    "logradouro": "Aracaju",
    "numero": 290,
    "complemento": "",
    "bairro": "Jardim Paulistano",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Benedito Aparecido de Almeida",
    "cpf": "580.726.328-68",
    "data_nasc": "02/07/1952",
    "email": "",
    "celular": 5515997548292,
    "logradouro": "Rua Lituânia",
    "numero": 870,
    "complemento": "",
    "bairro": "Jardim Guadalajara",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Camila Martins Rufino",
    "cpf": "324.986.238-09",
    "data_nasc": "03/10/1983",
    "email": "camila.ruf83@gmail.com",
    "celular": 5515981147634,
    "logradouro": "Curupaiti",
    "numero": 198,
    "complemento": "",
    "bairro": "Vila Jardini",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Caroline A. Tomaz",
    "cpf": "457.781.558-32",
    "data_nasc": "12/10/1997",
    "email": "carolineatmz@gmail.com",
    "celular": 5515981817073,
    "logradouro": "Comendador Pereira Inácio",
    "numero": "",
    "complemento": "",
    "bairro": "Jardim Santa Lucinda",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Carmen Teresa Almeida",
    "cpf": "985.695.898-9",
    "data_nasc": "02/06/1956",
    "email": "",
    "celular": 5515981484848,
    "logradouro": "Adolfo Claro de Almeida",
    "numero": 63,
    "complemento": "",
    "bairro": "Jardim Magnólia",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Célia Maria de Oliveira",
    "cpf": "589.338.168-87",
    "data_nasc": "17/07/1952",
    "email": "celiamoliveira1952@gmail.com",
    "celular": 5515997029792,
    "logradouro": "Amazonas",
    "numero": 141,
    "complemento": "",
    "bairro": "Vila Santa Terezinha",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Clisse Maria de Moraes Gomes",
    "cpf": "748.069.123-87",
    "data_nasc": "31/12/1973",
    "email": "clissemoraes@gmail.com",
    "celular": 5515996739270,
    "logradouro": "Egle Moreira Cardarelli",
    "numero": 96,
    "complemento": "",
    "bairro": "Jardim Alpes",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Cristiane Escudeiro",
    "cpf": "077.112.238-11",
    "data_nasc": "14/09/1966",
    "email": "cristianeescudeiro@eg.com.br",
    "celular": 5515991034242,
    "logradouro": "Rua Paschoal Alfredo Sorranz",
    "numero": 594,
    "complemento": "",
    "bairro": "Jardim São Paulo",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Cristiane Marques",
    "cpf": "138.921.528.31",
    "data_nasc": "20/10/1969",
    "email": "cristendencia2@gmail.com",
    "celular": 5515991166893,
    "logradouro": "Alameda das Primaveras",
    "numero": 603,
    "complemento": "apto 63",
    "bairro": "Jardim Simus",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Daniela Gomes Dias",
    "cpf": "222.050.298-86",
    "data_nasc": "08/08/1980",
    "email": "",
    "celular": 5515997757507,
    "logradouro": "Maria de Lourdes Teixeira",
    "numero": 217,
    "complemento": "",
    "bairro": "Reserva Fazenda Imperial",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Edivania Aparecida Eugênio da Silva",
    "cpf": "074.317.018-02",
    "data_nasc": "27/04/1970",
    "email": "edivaniaeugenios@gmail.com",
    "celular": 5515997308320,
    "logradouro": "Visconde de Cairu",
    "numero": 694,
    "complemento": "apto 01 bl 01",
    "bairro": "Mangal",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Fernanda de Jesus",
    "cpf": "122.918.788-08",
    "data_nasc": "03/04/1975",
    "email": "ferdiniz1975@outlook.com",
    "celular": 5515997558085,
    "logradouro": "Áureo Arruda",
    "numero": 675,
    "complemento": "",
    "bairro": "Júlio de Mesquita",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Gerson Soler",
    "cpf": "889.666.318-00",
    "data_nasc": "05/09/1956",
    "email": "solerparres@gmail.com",
    "celular": 5515997354926,
    "logradouro": "Sargento Jair Batista de Oliveira",
    "numero": "",
    "complemento": "",
    "bairro": "Residencial Vila dos Ingleses",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Helena Aparecida Facui",
    "cpf": "937.398.268-00",
    "data_nasc": "25/05/1957",
    "email": "helenafacui@hotmail.com",
    "celular": 5515981166940,
    "logradouro": "Luiz Silva Rodrigues",
    "numero": 384,
    "complemento": "apto 42",
    "bairro": "Vila Independência",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Jeanete Marcários Novo",
    "cpf": "141.757.918-84",
    "data_nasc": "28/04/1942",
    "email": "marcários.jeanete@gmail.com",
    "celular": 5515981330638,
    "logradouro": "Manoel Ferreira Leão",
    "numero": 67,
    "complemento": "apto 21",
    "bairro": "Vila Leão",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "José Ricardo Cordeiro Barros",
    "cpf": "091.345.788-46",
    "data_nasc": "03/06/1969",
    "email": "",
    "celular": 5515997012718,
    "logradouro": "Visconde do Rio Branco",
    "numero": 948,
    "complemento": "",
    "bairro": "Vila Jardini",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "José Vitor Mazon",
    "cpf": "053.199.988-61",
    "data_nasc": "24/10/1961",
    "email": "mazonvitor@gmail.com",
    "celular": 5515997753237,
    "logradouro": "Francisco Neves",
    "numero": "",
    "complemento": "",
    "bairro": "Campolim",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Larissa Silveira M. de Faria",
    "cpf": "470.343.428-81",
    "data_nasc": "13/12/1996",
    "email": "",
    "celular": 5519996149715,
    "logradouro": "Ipiranga",
    "numero": 265,
    "complemento": "",
    "bairro": "Vila Independência",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Lenita Gonçalves de Oliveira",
    "cpf": "099.322.848.82",
    "data_nasc": "10/03/1965",
    "email": "lenita@hotmail.com",
    "celular": 5515997894393,
    "logradouro": "Gustavo Teixeira",
    "numero": 159,
    "complemento": "",
    "bairro": "Vila Independência",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Lucimara Brasil",
    "cpf": "182.354.368.59",
    "data_nasc": "18/02/1975",
    "email": "",
    "celular": 5515998500800,
    "logradouro": "André Costa Dias",
    "numero": 57,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Luiz Alberto M. de Aguiar",
    "cpf": "750.773.298-34",
    "data_nasc": "21/03/1952",
    "email": "",
    "celular": 5515997851749,
    "logradouro": "Ipiranga",
    "numero": 265,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Luiz Cesar Pelicia",
    "cpf": "835.020.418-49",
    "data_nasc": "22/08/1956",
    "email": "bandaplataforma@hotmail.com",
    "celular": 5515997127632,
    "logradouro": "Raul Pompeia",
    "numero": 330,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Lúcia Tochie T. Muricava",
    "cpf": "144.915.178-78",
    "data_nasc": "08/08/1970",
    "email": "lucia.muricava@gmail.com",
    "celular": 5515998083535,
    "logradouro": "General Dale Coutinho",
    "numero": 106,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Márcia Brizolla Almeida",
    "cpf": "039.449.268-46",
    "data_nasc": "07/09/1964",
    "email": "",
    "celular": 5515997740508,
    "logradouro": "Savério Fazzio",
    "numero": 183,
    "complemento": "",
    "bairro": "Jardim Magnólia",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Maria Elisa P. Sinhoreli",
    "cpf": "089.801.038-16",
    "data_nasc": "21/10/1966",
    "email": "elisa.sinhoreli@gmail.com",
    "celular": 5515997081954,
    "logradouro": "Rua Luiz da Silva Rodrigues",
    "numero": 564,
    "complemento": "apto 2",
    "bairro": "Vila Independência",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Maria Isabel Martines",
    "cpf": "021.229.918-28",
    "data_nasc": "06/12/1956",
    "email": "belmartines@gmail.com",
    "celular": 5515997110788,
    "logradouro": "Humberto de Campos",
    "numero": 755,
    "complemento": "casa 2",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Marystela Ferreira",
    "cpf": "181.111.188-21",
    "data_nasc": "12/07/1971",
    "email": "marystela.ferreira@gmail.com",
    "celular": 5515981295336,
    "logradouro": "Eulófia Mora Vieira",
    "numero": 175,
    "complemento": "casa A5",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Maria Inês Luchini",
    "cpf": "074.309.828-59",
    "data_nasc": "26/08/1962",
    "email": "mi.luchini@gmail.com",
    "celular": 5515997730506,
    "logradouro": "Cap. Gramdino",
    "numero": 432,
    "complemento": "apto 32",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Marcia Kimie Tanabe",
    "cpf": "122.612.108-09",
    "data_nasc": "25/12/1967",
    "email": "tanabe.marcia@gmail.com",
    "celular": 5515997019220,
    "logradouro": "Luiz Silva Rodrigues",
    "numero": 504,
    "complemento": "",
    "bairro": "Vila Independência",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Maria Sueli Santos",
    "cpf": "021.187.068-47",
    "data_nasc": "14/07/1956",
    "email": "",
    "celular": 5515988080142,
    "logradouro": "Icarai",
    "numero": 326,
    "complemento": "",
    "bairro": "Vila Jardini",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Milena Silva Rios",
    "cpf": "116.438.748-02",
    "data_nasc": "25/09/1972",
    "email": "mila.sv.72@hotmail.com",
    "celular": 5515991040714,
    "logradouro": "Guarapes",
    "numero": 157,
    "complemento": "",
    "bairro": "Vila Jardini",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Maria da Penha Santos H. Reis",
    "cpf": "116.239.458-79",
    "data_nasc": "17/03/1971",
    "email": "penhasantos2009@hotmail.com",
    "celular": 5515981706079,
    "logradouro": "João Martini Filho",
    "numero": 693,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Mônica Cristiane Fernando",
    "cpf": "171.689.278-81",
    "data_nasc": "29/07/1968",
    "email": "monicafernando.doi@icloud.com",
    "celular": 5515998227575,
    "logradouro": "Sargento V. Barbosa",
    "numero": 453,
    "complemento": "apto 81",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Newton Ramos",
    "cpf": "081.868.518-26",
    "data_nasc": "16/09/1966",
    "email": "newtonpublico@mol.com.br",
    "celular": 5515996051666,
    "logradouro": "Estrada Jovina de Barros Simôes",
    "numero": 600,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Ozeas Santos Filho",
    "cpf": "834.761.808-91",
    "data_nasc": "04/05/1954",
    "email": "",
    "celular": "",
    "logradouro": "Icarai",
    "numero": 326,
    "complemento": "",
    "bairro": "Vila Jardini",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Roseli Maria Gonçalves",
    "cpf": "430.010.419-00",
    "data_nasc": "03/07/1961",
    "email": "",
    "celular": 5515981609912,
    "logradouro": "Ipiranga",
    "numero": 302,
    "complemento": "apto 52",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Renata Randazzo",
    "cpf": "049.143.088-43",
    "data_nasc": "21/05/1967",
    "email": "randazzorenata@gmail.com",
    "celular": 5515997811014,
    "logradouro": "Visconde de Cairu",
    "numero": 694,
    "complemento": "apto 32 bl 01",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Roberta Ramos",
    "cpf": "373.635.638-29",
    "data_nasc": "27/07/1986",
    "email": "roberta.ramosdodo@gmail.com",
    "celular": 5515997434439,
    "logradouro": "Estrada Jovina de Barros Simôes",
    "numero": 600,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Sueli de Fatima Dias",
    "cpf": "122.525.445-57",
    "data_nasc": "28/06/1968",
    "email": "",
    "celular": 5515997075539,
    "logradouro": "Ramadu 3",
    "numero": "",
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Sandra Rosa",
    "cpf": "032.439.848-40",
    "data_nasc": "14/10/1960",
    "email": "sandrazzchetti@hotmail.com",
    "celular": 5515991018947,
    "logradouro": "Visconde do Rio Branco",
    "numero": 681,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Shirley de Almeida",
    "cpf": "821.575.708-10",
    "data_nasc": "22/11/1954",
    "email": "",
    "celular": 5515997881128,
    "logradouro": "Lituânia",
    "numero": 870,
    "complemento": "",
    "bairro": "Jardim Guadalajara",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Sonia Maria",
    "cpf": "752.803.298-60",
    "data_nasc": "22/12/1954",
    "email": "",
    "celular": 5515991164798,
    "logradouro": "",
    "numero": 65,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Soraia Ogusuku",
    "cpf": "197.299.948-62",
    "data_nasc": "25/07/1972",
    "email": "sraia.ogusuku@gmail.com",
    "celular": 5515997121471,
    "logradouro": "Rua Guarani",
    "numero": 212,
    "complemento": "",
    "bairro": "Vila Jardini",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Symone Nunes",
    "cpf": "085.159.578-25",
    "data_nasc": "16/05/1965",
    "email": "morenn1@hotmail.com",
    "celular": 5515991440011,
    "logradouro": "Deputado Mazilli",
    "numero": 675,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Terezinha Cordeiro de Barros",
    "cpf": "262.925.968-42",
    "data_nasc": "03/10/1942",
    "email": "",
    "celular": 5515997012718,
    "logradouro": "Visconde do Rio Branco",
    "numero": 948,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Vera Cristina da S.",
    "cpf": "770.284.098-82",
    "data_nasc": "01/09/1953",
    "email": "ingrid.levi@hotmail.com",
    "celular": 5515997723232,
    "logradouro": "Luiz Silva Rodrigues",
    "numero": 385,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Vicente Arfeu Somaio",
    "cpf": "031.763.298-00",
    "data_nasc": "19/11/1931",
    "email": "cristianeescudeiro@eg.com.br",
    "celular": 5515991140814,
    "logradouro": "",
    "numero": "",
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Vittor Pires da Silva",
    "cpf": "660.692.628-91",
    "data_nasc": "16/02/1943",
    "email": "",
    "celular": 5515997964302,
    "logradouro": "Aracaju",
    "numero": 146,
    "complemento": "",
    "bairro": "Jardim Paulistano",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Zilza Gonzaga Leite",
    "cpf": "161.043.508-62",
    "data_nasc": "11/08/1962",
    "email": "zilsder@gmail.com",
    "celular": 5515991841353,
    "logradouro": "",
    "numero": "",
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Elias Carui",
    "cpf": "526.992.428-53",
    "data_nasc": "21/05/1945",
    "email": "ecarui@terra.com.br",
    "celular": 5515997146638,
    "logradouro": "Aracaju",
    "numero": 130,
    "complemento": "",
    "bairro": "Jardim Paulistano",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Cicera Rordigues de Mattos",
    "cpf": "042.138.618-54",
    "data_nasc": "22/08/1962",
    "email": "ci.mattosgoes@gmail.com",
    "celular": 5515988013678,
    "logradouro": "Francisca Clara da Silva",
    "numero": 94,
    "complemento": "",
    "bairro": "",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Paulo  Prudencio de Souza",
    "cpf": "042.314.738-20",
    "data_nasc": "10/04/1946",
    "email": "",
    "celular": 5515998429929,
    "logradouro": "Grécia",
    "numero": 135,
    "complemento": "",
    "bairro": "Jardim Europa",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Elizabeth Marinho de Souza",
    "cpf": "903.701.398-87",
    "data_nasc": "10/11/1949",
    "email": "pauloelisabeth@gmail.com",
    "celular": 5511998429929,
    "logradouro": "Grécia",
    "numero": 135,
    "complemento": "",
    "bairro": "Jardim Europa",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "Marcia Franco",
    "cpf": "106.114.978-16",
    "data_nasc": "29/01/1967",
    "email": "marcia.n_nicolau@hotmail.com",
    "celular": 5515991315114,
    "logradouro": "Contídio de Moura Campos",
    "numero": 180,
    "complemento": "",
    "bairro": "Vila Jardini",
    "cidade": "Sorocaba",
    "uf": "SP",
    "cep": "",
    "lim_aulas": ""
  },
  {
    "nome": "",
    "cpf": "",
    "data_nasc": "",
    "email": "",
    "celular": "",
    "logradouro": "",
    "numero": "",
    "complemento": "",
    "bairro": "",
    "cidade": "",
    "uf": "",
    "cep": "",
    "lim_aulas": ""
  }
];

const ImportadorDB = () => {
  const [carregando, setCarregando] = useState(false);

  const injetarDados = () => {
    if (ALUNOS_CARGA_INICIAL.length === 0) {
      Alert.alert("Atenção", "O array de alunos está vazio. Cole o JSON primeiro.");
      return;
    }

    Alert.alert(
      "Confirmar Carga",
      `Deseja injetar ${ALUNOS_CARGA_INICIAL.length} alunos no banco de dados agora?`,
      [
        { text: "Cancelar", style: "cancel" },
        { 
          text: "Injetar", 
          onPress: () => processarInjecao() 
        }
      ]
    );
  };

  const processarInjecao = () => {
    setCarregando(true);

    db.transaction((tx) => {
      ALUNOS_CARGA_INICIAL.forEach((aluno) => {
        
        if (!aluno.cpf) return;

        tx.executeSql(
          `INSERT INTO alunos (nome, cpf, data_nasc, email, celular, logradouro, numero, complemento, bairro, cidade, uf, cep, lim_aulas, ativo) 
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)`,
          [
            aluno.nome || '', 
            aluno.cpf || '', 
            aluno.data_nasc || null, 
            aluno.email || null, 
            aluno.celular || null, 
            aluno.logradouro || null, 
            aluno.numero || null, 
            aluno.complemento || null, 
            aluno.bairro || null, 
            aluno.cidade || null, 
            aluno.uf || null, 
            aluno.cep || null, 
            parseInt(aluno.lim_aulas) || 0
          ],
          () => {  },
        );
      });
    }, 
    (error) => {
      setCarregando(false);
      Alert.alert("Erro fatal", "A transação falhou: " + error.message);
    }, 
    () => {
      setCarregando(false);
      Alert.alert(
        "Missão Cumprida! 🚀", 
        `Todos os ${ALUNOS_CARGA_INICIAL.length} alunos foram processados com sucesso.\n\nO banco SQLite já está populado. Você já pode fechar esta tela e acessar a Gestão de Alunos.`,
        [{ text: "OK" }]
      );
    });
  };

  return (
    <View style={styles.container}>
      <Icon name="database" size={80} color="#007bff" style={{ marginBottom: 20 }} />
      <Text style={styles.title}>Carga Inicial do Sistema</Text>
      <Text style={styles.subtitle}>
        Este módulo lerá a lista de alunos embutido no código e fará a injeção inicial de dados no app.
      </Text>

      {carregando ? (
        <ActivityIndicator size="large" color="#007bff" style={{ marginTop: 30 }} />
      ) : (
        <TouchableOpacity style={styles.btnInjetar} onPress={injetarDados}>
          <Text style={styles.btnText}>INJETAR DADOS AGORA</Text>
        </TouchableOpacity>
      )}

      
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 24,
  },
  btnInjetar: {
    backgroundColor: '#FF3B30', 
    paddingVertical: 18,
    paddingHorizontal: 30,
    borderRadius: 12,
    elevation: 4,
  },
  btnText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
    letterSpacing: 1,
  },
  warning: {
    marginTop: 40,
    fontSize: 14,
    color: '#999',
    fontStyle: 'italic',
    textAlign: 'center',
  }
});

export default ImportadorDB;